# This is a simple example Ansible playbook
---
- name: Starting Flask Webserver Microservice
  hosts: all
  remote_user: root
  become: true
  become_method: sudo
  environment: 
    LC_ALL: en_US.UTF-8
    LANG: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
  vars:
      repository_url: https://github.com/chrisroman/CloudComputing.git
      repository_path: /home/ec2-user/CloudComputing
      flask_app_path: /home/ec2-user/CloudComputing/Server
      gunicorn_start_path: /home/ec2-user/CloudComputing/Server/src
  tasks:
    - name: Install necessary packages
      yum: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - docker
        - python-pip
    - name: Install docker-py
      pip:
          name: docker-py
          state: present
    - name: Check if directory exists
      stat: path='{{ repository_path }}'
      register: cloned
    - name: Pull application repo
      command: chdir='{{ repository_path }}' git pull origin master
      when: cloned.stat.exists
    - name: Clone application repo
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'
      when: cloned.stat.exists == false
    - name: Start Docker service
      service:
          name: docker
          state: started
    - name: Run Docker Container
      command: chdir='{{ repository_path }}' docker run -d --name webserver -p 80:80 chrisroman/cloudcomputing:latest
